# Generated by Django 4.2.13 on 2024-06-02 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio_actual', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('foto_identificacion', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_imei', models.CharField(max_length=255)),
                ('equipo_a_adquirir', models.CharField(max_length=255)),
                ('monto_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo_credito', models.IntegerField()),
                ('pago_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.cliente')),
            ],
        ),
    ]
