# Generated by Django 4.2.13 on 2024-06-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto_identificacion',
            field=models.ImageField(blank=True, null=True, upload_to='clientes_identificaciones/'),
        ),
    ]
