# Generated by Django 4.2.13 on 2024-06-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_cliente_foto_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='equipo_precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
