# Generated by Django 4.2.13 on 2024-06-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_prestamo_equipo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='equipo_precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
