# Generated by Django 4.2.13 on 2024-06-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_prestamo_equipo_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='equipo_imei',
            new_name='imei',
        ),
    ]
