# Generated by Django 4.2.13 on 2024-06-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_rename_cliente_prestamo_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
