# Generated by Django 4.2.13 on 2024-06-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_rename_cliente_id_prestamo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clave_elector',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
