# Generated by Django 4.2.13 on 2024-06-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_cliente_clave_elector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clave_elector',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
