# Generated by Django 4.2.13 on 2024-07-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_alter_cliente_clave_elector'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_primer_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
