# Generated by Django 4.2.13 on 2024-07-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_prestamo_fecha_primer_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_primer_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
